seed: 0
deterministic: false

checkpoint_config:
  interval: 1
  max_keep_ckpts: 1

log_config:
  interval: 100
  hooks:
    -
      type: TextLoggerHook
    -
      type: TensorboardLoggerHook

load_from: null
resume_from: /data0/junzhiguan/bevfusion/runs/camera_seg_0.2_0.1_2024-02-05_infer/latest.pth

cudnn_benchmark: false
fp16:
  loss_scale: 
    growth_interval: 2000

max_epochs: 40
runner:
  type: CustomEpochBasedRunner
  max_epochs: ${max_epochs}
